name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  android:
    name: Android App Build
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: whoami
        run: whoami

      - name: cd
        run: cd ~ && pwd && ls

      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: dev-terakawa/actions
          ref: master
          token: ${{ secrets.GIT_TOKEN }}

      - name: ls
        run: ls -la /home/runner/ && ls -la /home/runner/work/ && ls -la /home/runner/work/SampleAndroid/

      #      - name: Hello world action step
      #        id: hello
      #        uses: dev-terakawa/actions@master
      #        with:
      #          who-to-greet: 'Mona the Octocat'
      #
      #      # Use the output from the `hello` step
      #      - name: Get the output time
      #        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Trigger Branch
        run: echo ${GITHUB_REF} ${GITHUB_EVENT_NAME}

      # master以外すべて
      - name: Build Debug
        if: contains(github.ref, 'refs/heads/master') == false
        run: ./gradlew assembleDebug

      # masterのときだけ
      - name: Build Release
        if: contains(github.ref, 'refs/heads/master')
        run: ./gradlew assembleRelease

      - name: SonarQube
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: app/build/outputs