name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  android:
    name: Android App Build
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      # cleanいらなそう
      - name: Clean
        run: ./gradlew clean

      - name: Sample
        run: echo ${GITHUB_REF} ${GITHUB_REPOSITORY}

      - name: Build Debug
        if: github.ref != 'master'
        run: ./gradlew assembleDebug

      - name: Build Release
        if: github.ref == 'master'
        run: ./gradlew assembleRelease

      - name: Unit Test
        run: ./gradlew test

      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: app/build/outputs