name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  android:
    name: Android App Build
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Trigger Branch
        run: echo ${GITHUB_REF} ${GITHUB_EVENT_NAME}

      # master以外すべて
      - name: Build Debug
        if: contains(github.ref, 'refs/heads/master') == false
        run: ./gradlew assembleDebug

      # masterのときだけ
      - name: Build Release
        if: contains(github.ref, 'refs/heads/master')
        run: ./gradlew assembleRelease

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: app/build/outputs