name: Develop

on:
  push:
    branches:
      - develop

jobs:
  develop:
    name: Android Develop Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macOS-10.14]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Credentials
        run: 'curl -H "Authorization: token ${{ secrets.GIT_TOKEN }}" -O https://raw.githubusercontent.com/dev-terakawa/Credentialfiles/master/README.md'

      - name: DL check
        run: cat README.md

      #      - name: Checkout
      #        uses: actions/checkout@v1
      #        with:
      #          repository: dev-terakawa/actions
      #          ref: master
      #          token: ${{ secrets.GIT_TOKEN }}

      - name: ls
        run: ls -la /home/runner/work/SampleAndroid/ && ls -la /home/runner/work/SampleAndroid/SampleAndroid/

      - name: Hello world action step
        id: hello
        uses: dev-terakawa/actions/js@master
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Trigger Branch
        run: echo ${GITHUB_REF} ${GITHUB_EVENT_NAME} ${HOME} ${GITHUB_ACTION}

      # master以外すべて
      - name: Build Debug
        if: contains(github.ref, 'refs/heads/master') == false
        run: ./gradlew assembleDebug

      - name: ls
        run: ls -la ~/

      - name: SonarQube
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: app/build/outputs