name: Develop

on:
  push:
    branches:
      - develop

jobs:
  develop:
    name: Develop Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]

    steps:
      - name: machine
        run: echo ${{ matrix.os }}
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Credentials
        run: 'curl -H "Authorization: token ${{ secrets.GIT_TOKEN }}" -O https://raw.githubusercontent.com/dev-terakawa/Credentialfiles/master/README.md'

      - name: DL check
        run: cat README.md

      #      - name: Checkout
      #        uses: actions/checkout@v1
      #        with:
      #          repository: dev-terakawa/actions
      #          ref: master
      #          token: ${{ secrets.GIT_TOKEN }}

      - name: current dir
        run: echo "::set-env name=PWD::$(pwd)"

      - name: ls
        run: "ls -la ${PWD}"

      - name: Hello world action step
        id: hello
        uses: dev-terakawa/actions/js@master
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Trigger Branch
        run: echo ${GITHUB_REF} ${GITHUB_EVENT_NAME} ${HOME} ${GITHUB_ACTION}

      # master以外すべて
      - name: Build Debug
        if: contains(github.ref, 'refs/heads/master') == false
        run: ./gradlew assembleDebug

      - name: check .android
        run: ls -la ~/

      - name: SonarQube
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: app/build/outputs